# Generated by Django 3.1.5 on 2021-06-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
