# Generated by Django 3.1.5 on 2021-06-09 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210608_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='quser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quser',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quser',
            name='last_naem',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
