# Generated by Django 3.2.4 on 2021-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210609_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
