# Generated by Django 3.2.4 on 2021-06-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20210609_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='downvote',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvote',
        ),
    ]
