# Generated by Django 3.2.4 on 2021-06-12 05:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20210609_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('-id',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='tags',
            name='detail',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
